name: Hardhat Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20 # You can specify your Node.js version here

      - name: Install Dependencies
        run: npm install

      - name: Run Hardhat Tests
        run: npx hardhat test
        with:
          PRIVATE_KEY: ${{env.PRIVATE_KEY}}
          PINATA_API_KEY: ${{env.PINATA_API_KEY}}
